# Generated by Django 4.2.2 on 2023-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_alter_userinfo_email_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
