# Generated by Django 4.2.2 on 2023-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
