# Generated by Django 4.2.2 on 2023-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
