# Generated by Django 4.2.2 on 2023-07-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0007_alter_userbar_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbar',
            old_name='bars',
            new_name='bar',
        ),
    ]
